import type Database from 'better-sqlite3';

export const version = 2;

export function up(db: Database.Database): void {
  // Durable metadata table — keyed by stable (provider, external_id).
  // This table is NEVER dropped by reindex. It survives deleteAllData().
  // The join to sessions is via (provider, external_id), NOT via sessions.id.
  db.exec(`
    CREATE TABLE session_meta (
      provider TEXT NOT NULL,
      external_id TEXT NOT NULL,
      title TEXT,
      hidden INTEGER NOT NULL DEFAULT 0,
      archived INTEGER NOT NULL DEFAULT 0,
      auto_commit INTEGER,
      auto_branch INTEGER,
      auto_document INTEGER,
      auto_compact INTEGER,
      draft TEXT,
      model_override TEXT,
      custom_instructions TEXT,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL,
      PRIMARY KEY (provider, external_id)
    );

    CREATE INDEX idx_session_meta_updated ON session_meta(updated_at DESC);
  `);

  // Seed session_meta from existing sessions that have user-generated titles
  // (titles generated by the daemon during indexing)
  db.exec(`
    INSERT OR IGNORE INTO session_meta (provider, external_id, title, created_at, updated_at)
    SELECT provider, external_id, title, created_at, updated_at
    FROM sessions
    WHERE title IS NOT NULL
  `);
}
